config/routes.rb
Rails.application.routes.draw do
  get 'favorites/create'
  get 'favorites/destroy'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'animals#index'
  resources :animals do
    get "following_animals" => "animals#following_animals"

    resource :favorites, only: [:create, :destroy, :show]
    resources :comments, only: :create
    collection do
      get 'search'
    end
  end
  resources :users do
    resource :relationships, only: [:create, :destroy]
  get 'followings' => 'relationships#followings', as: 'followings'
  get 'followers' => 'relationships#followers', as: 'followers'
  
  end

end

app/models/animal.rb
class Animal < ApplicationRecord
  belongs_to :user
  has_many :animal_tag_relations,foreign_key: :animal_id, dependent: :destroy
  has_many :tags, through: :animal_tag_relations
  has_many :comments,foreign_key: :animal_id, dependent: :destroy
  has_many :favorites
  has_one_attached :image

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end



  def self.search(search)
    if search != ""
      Animal.where('tweet LIKE(?)', "%#{search}%")
    else
      Animal.all
    end
  end
end

app/models/animal_tag_relation.rb
class AnimalTagRelation < ApplicationRecord
  belongs_to :animal
  belongs_to :tag
end

app/models/animals_tag.rb
class AnimalsTag

  include ActiveModel::Model
  attr_accessor :image,:tweet, :name,:user_id

  with_options presence: true do
    validates :user_id
    validates :image  
  end
  validates :tweet, length: { maximum: 75 } 


  def save
    animal = Animal.create(tweet: tweet,image: image,user_id: user_id)
    tag = Tag.where(name: name).first_or_initialize
    tag.save

    AnimalTagRelation.create(animal_id: animal.id, tag_id: tag.id)
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :animal
  belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :animal
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :animal_tag_relations
  has_many :animals, through: :animal_tag_relations

  validates :name, uniqueness: true

  def self.search(search)
    if search != '#'
      tag = Tag.where(name: search)
      tag[0].animals
    else
      Animals.all
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :animals,foreign_key: :user_id, dependent: :destroy
         has_many :favorites
         has_many :favorite_animals, through: :favorites, source: :animal 
         has_many :comments
         has_one_attached :image

         has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
         has_many :followers, through: :reverse_of_relationships, source: :follower

         has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
         has_many :followings, through: :relationships, source: :followed

         with_options presence: true do
          validates :nickname

         end

         def follow(user_id)
          relationships.create(followed_id: user_id)
        end
        def unfollow(user_id)
          relationships.find_by(followed_id: user_id).destroy
        end
        def following?(user)
          followings.include?(user)
        end        
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :authenticate_user!, only: [:index]
  before_action :set_animal, only: [:edit, :show]
  before_action :move_to_index, except: [:index, :show, :search]  

  def index
    @animals = Animal.includes(:user).order("created_at DESC")
    @user = current_user.id
  end

  def following_animals
    @user = current_user
    @users = @user.followings.order("created_at DESC")
  end

  def new
    @animal_tag = AnimalsTag.new
  end

  def create
    @animal_tag = AnimalsTag.new(animal_params)
    if @animal_tag.valid?
      @animal_tag.save
       redirect_to root_path
    else
      render :new
    end
  end
  

  def destroy
    animal = Animal.find(params[:id])
    animal.destroy
  end

  def edit
    
  end

  def update
    animal = Animal.find(params[:id])
    animal.update(animal_params)
  end
  
  def show
    @comment = Comment.new
    @comments = @animal.comments.includes(:user)
  end

  def search
    if (params[:keyword])[0] == '#'
      @animals = Tag.search(params[:keyword]).order('created_at DESC')
    else
      @animals = Animal.search(params[:keyword]).order('created_at DESC')
  end
end
  

  private
  def animal_params
    params.require(:animals_tag).permit(:image, :tweet, :name).merge(user_id: current_user.id)
  end
  
  def set_animal
    @animal = Animal.find(params[:id])
  end
  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == 'hirano' && password == '1312'
    end
  end

  before_action :configure_permitted_parameters, if: :devise_controller?
  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to "/animals/#{comment.animal.id}"
    end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, animal_id: params[:animal_id])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.build(animal_id: params[:animal_id])
    favorite.save
    redirect_to animals_path
  end

  def destroy
    favorite = Favorite.find_by(animal_id: params[:animal_id], user_id: current_user.id)
    favorite.destroy
    redirect_to animals_path
  end

  def show
   @animals = current_user.animals
   @favorite_animals = current_user.favorite_animals
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = current_user.followings
  end
  
  def show
    @user = User.find(params[:id])
    @animal = @user.animals
    @favorite_animals = @user.favorite_animals
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
   else
    render :edit
   end
  end

  private
  def user_params
    params.require(:user).permit(:nickname,:image,:profile)
  end

end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ber/_sideber.html.erb
    <!--サイドバー-->
  <div class="openbtn" id="opendtn"><span></span>
                       <span></span>
                       <span></span>
  </div>
<nav id="g-nav">
<div class='side'>
  <div class='user-img'>
  <% if current_user.image.present? %>
    <%= image_tag current_user.image %>
    <% else %>
    <%= image_tag "dummy_user.png" %>
    <% end %>
    </div>
    <div class='user-name'>
    <a><%= current_user.nickname %> </a>
    </div>
<div class='user-list'>
<ul>
<li><%= link_to "マイページ", user_path(current_user.id) %></li> 
<li><%= link_to "フォロー", animal_following_animals_path(current_user.id) %></li> 
<li><%= link_to "投稿する", new_animal_path %></li> 
<li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li> 
<li><%= link_to "お気に入り", animal_favorites_path(current_user.id) %></li> 
</ul>
</div>
</div>
</div>
</nav>
<!--自作のJS-->
<script src="js/5-1-13.js"></script>
<!--サイドバー-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AnimalResidence</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
        <link href="https://coco-factory.jp/ugokuweb/wp-content/themes/ugokuweb/data/reset.css" rel="stylesheet">
      <link href="https://coco-factory.jp/ugokuweb/wp-content/themes/ugokuweb/data/4-1-4/css/4-1-4.css" rel="stylesheet">
      <link rel="stylesheet" type="text/css" href="css/4-1-4.css">
      <link rel="stylesheet" type="text/css" href="css/5-1-13.css">
</head>
  </head>
  <body>
      <header class="header">
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/">AnimalResidence</a></h1>
        <% if user_signed_in? %>
          <div class="user_nav ">
          <%= form_with(url: search_animals_path, local: true, method: :get, class: "search-form") do |form| %>
          <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
          <%= form.submit "検索", class: "search-btn" %>
          <% end %>
          </div>
        <% else %>
          <div class="grid-6">
            <%= link_to "ログイン", new_user_session_path, class: "post" %>
            <%= link_to "新規登録", new_user_registration_path, class: "post" %>
          </div>
        <% end %>
       </div>
    </header>
    <%= yield %>
        <footer>
      <p>
        © 2021 MB inc.
      </p>
    </footer>

    </body>
</html>