config/routes.rb
Rails.application.routes.draw do
  get 'favorites/create'
  get 'favorites/destroy'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'animals#index'
  resources :animals do
    get "following_animals" => "animals#following_animals"

    resource :favorites, only: [:create, :destroy, :show]
    resources :comments, only: :create
    collection do
      get 'search'
    end
  end
  resources :users do
    resource :relationships, only: [:create, :destroy]
  get 'followings' => 'relationships#followings', as: 'followings'
  get 'followers' => 'relationships#followers', as: 'followers'
  
  end

end

app/models/animal.rb
class Animal < ApplicationRecord
  belongs_to :user
  has_many :animal_tag_relations,foreign_key: :animal_id, dependent: :destroy
  has_many :tags, through: :animal_tag_relations
  has_many :comments,foreign_key: :animal_id, dependent: :destroy
  has_many :favorites
  has_one_attached :image

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end



  def self.search(search)
    if search != ""
      Animal.where('tweet LIKE(?)', "%#{search}%")
    else
      Animal.all
    end
  end
end

app/models/animal_tag_relation.rb
class AnimalTagRelation < ApplicationRecord
  belongs_to :animal
  belongs_to :tag
end

app/models/animals_tag.rb
class AnimalsTag

  include ActiveModel::Model
  attr_accessor :image,:tweet, :name,:user_id

  with_options presence: true do
    validates :user_id
    validates :image  
  end
  validates :tweet, length: { maximum: 75 } 


  def save
    animal = Animal.create(tweet: tweet,image: image,user_id: user_id)
    tag = Tag.where(name: name).first_or_initialize
    tag.save

    AnimalTagRelation.create(animal_id: animal.id, tag_id: tag.id)
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :animal
  belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :animal
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :animal_tag_relations
  has_many :animals, through: :animal_tag_relations

  validates :name, uniqueness: true

  def self.search(search)
    if search != '#'
      tag = Tag.where(name: search)
      tag[0].animals
    else
      Animals.all
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :animals,foreign_key: :user_id, dependent: :destroy
         has_many :favorites
         has_many :favorite_animals, through: :favorites, source: :animal 
         has_many :comments
         has_one_attached :image

         has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
         has_many :followers, through: :reverse_of_relationships, source: :follower

         has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
         has_many :followings, through: :relationships, source: :followed

         with_options presence: true do
          validates :nickname

         end

         def follow(user_id)
          relationships.create(followed_id: user_id)
        end
        def unfollow(user_id)
          relationships.find_by(followed_id: user_id).destroy
        end
        def following?(user)
          followings.include?(user)
        end        
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :authenticate_user!, only: [:index]
  before_action :set_animal, only: [:edit, :show]
  before_action :move_to_index, except: [:index, :show, :search]  

  def index
    @animals = Animal.includes(:user).order("created_at DESC")
    @user = current_user.id
  end

  def following_animals
    @user = current_user
    @users = @user.followings.order("created_at DESC")
  end

  def new
    @animal_tag = AnimalsTag.new
  end

  def create
    @animal_tag = AnimalsTag.new(animal_params)
    if @animal_tag.valid?
      @animal_tag.save
       redirect_to root_path
    else
      render :new
    end
  end
  

  def destroy
    animal = Animal.find(params[:id])
    animal.destroy
  end

  def edit
    
  end

  def update
    animal = Animal.find(params[:id])
    animal.update(animal_params)
  end
  
  def show
    @comment = Comment.new
    @comments = @animal.comments.includes(:user)
  end

  def search
    if (params[:keyword])[0] == '#'
      @animals = Tag.search(params[:keyword]).order('created_at DESC')
    else
      @animals = Animal.search(params[:keyword]).order('created_at DESC')
  end
end
  

  private
  def animal_params
    params.require(:animals_tag).permit(:image, :tweet, :name).merge(user_id: current_user.id)
  end
  
  def set_animal
    @animal = Animal.find(params[:id])
  end
  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == 'hirano' && password == '1312'
    end
  end

  before_action :configure_permitted_parameters, if: :devise_controller?
  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to "/animals/#{comment.animal.id}"
    end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, animal_id: params[:animal_id])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.build(animal_id: params[:animal_id])
    favorite.save
    redirect_to animals_path
  end

  def destroy
    favorite = Favorite.find_by(animal_id: params[:animal_id], user_id: current_user.id)
    favorite.destroy
    redirect_to animals_path
  end

  def show
   @animals = current_user.animals
   @favorite_animals = current_user.favorite_animals
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

# ——————フォロー機能を作成・保存・削除する————————————
def create
  current_user.follow(params[:user_id])
  redirect_to request.referer
end

def destroy
  current_user.unfollow(params[:user_id])
  redirect_to request.referer  
end
#————————フォロー・フォロワー一覧を表示する-————————————
def followings
  user = User.find(params[:user_id])
  @users = user.followings
end

def followers
  user = User.find(params[:user_id])
  @users = user.followers
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = current_user.followings
  end
  
  def show
    @user = User.find(params[:id])
    @animal = @user.animals
    @favorite_animals = @user.favorite_animals
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
   else
    render :edit
   end
  end

  private
  def user_params
    params.require(:user).permit(:nickname,:image,:profile)
  end

end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/animals/_animal.html.erb
<div class='animal-content'>
  <div class='user-content'>
    <div class='user-img-content'>
    <% if animal.user.image.present? %>
    <%= image_tag animal.user.image, class: "item-img" %>
    <% else %>
    <%= image_tag "dummy_user.png", class: "item-img" %>
    <% end %>
    </div>
  <% if current_user.id != animal.user.id? %>
    <div class="follow">
    <%= render "relationships/follow_button", user: animal.user %>
    </div>
  <% end %>
  </div>
    <div class="content_post">
      <div class="fav">
      <%= render partial: "favorites/favorite", locals: { animal: animal } %>
      </div>
      <span class="name">
        <a href="/users/<%= animal.user.id %>">
        <%= animal.user.nickname %>
        </a>
        <p><%= safe_join(animal.tweet.split("\n"),tag(:br)) %></p>
        <p><% animal.tags.each do |tag| %>
        <%=link_to tag.name, search_animals_path(keyword: tag.name) %>
        <%end%>
        </p>
      </span>
    <%= link_to image_tag(animal.image, class: 'animalpic'),animal_path(animal.id) %>
    </div>
  </div>
</div>

app/views/animals/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/animals/_form.html.erb
  <%= form_with model: @animal_tag, url: animals_path, local: true do |form| %>
  
  <%= render 'error_messages', model: form.object %>

        AnimalPicture
        <span class="indispensable">必須</span>
      <div class="click-upload">
      クリックしてファイルをアップロード
        <%= form.file_field :image, id:"select-image" %>
    </div>
        <div class= "preview">
        <%= image_tag 'pure.png' %>
        <div id="image-list">
        </div>
        </div>
    text
      <%= form.text_area :tweet, rows: "5" %>
    tag
    <span class="indispensable">先頭に「#」を記載してください</span>
      <%= form.text_area :name, rows: "1" %>
      <div id="search-result">
    </div>
      <%= form.submit "投稿" %>
    <% end %>

app/views/animals/create.html.erb
<div class="contents row">
  <div class="success">
    <h3>投稿が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/animals/destroy.html.erb
<div class="contents row">
  <div class="success">
    <h3>削除が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/animals/following_animals.html.erb
<div class="contents row">
<% if @users.exists? %>
  <% @users.each do |user| %>
  <% @animals = Animal.where(user_id: user.id).limit(1).order("created_at DESC") %>
  <% @animals.each do |animal| %>
   <%= render partial: "animal", locals: { animal: animal } %>
  <% end %>
  <% end %>
  <% else %>
  <p>ユーザーはいません</p>
<% end %>
</div>

  <%= link_to(new_animal_path, class: 'animal-btn') do %>
  <%= image_tag 'icon.png' , size: '185x50'%>
  <% end %>
</div>

app/views/animals/index.html.erb
   <div id="splash">
    <div id="splash_logo">
    <%= image_tag 'logo_white.png', class:"fadeUp" %> 
    </div>
  </div>
<div class="contents row">
  <% @animals.each do |animal| %>
   <%= render partial: "animal", locals: { animal: animal } %>
  <% end %>
  <%= link_to(new_animal_path, class: 'animal-btn') do %>
  <%= image_tag 'icon.png' , size: '185x50'%>
  <% end %>
</div>
<%= render partial: "ber/sideber"%>
<script src="https://code.jquery.com/jquery-3.4.1.min.js"
    integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
  <script src="https://coco-factory.jp/ugokuweb/wp-content/themes/ugokuweb/data/4-1-4/js/4-1-4.js"></script>

app/views/animals/new.html.erb
<div class="contents row ">
  <div class="container">
    <h3>投稿する</h3>
    <%= render partial: "form", locals: { animal_tag: @animal_tag } %>
  </div>
</div>
<%= render partial: "ber/sideber"%>

app/views/animals/search.html.erb
<%= form_with(url: search_animals_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>
</div>
<div class="contents row">
   <% @animals.each do |animal| %>
    <%= render partial: "animal", locals: { animal: animal } %>
  <% end %>
</div>
<%= render partial: "ber/sideber"%>

app/views/animals/show.html.erb
<div class="contents row">
<div class='animal-content'>
<div class='user-content'>
  <div class='user-img-content'>
    <% if @animal.user.image.present? %>
    <%= image_tag @animal.user.image%>
    <% else %>
    <%= image_tag "dummy_user.png" %>
    <% end %>
    </div>
    <% if current_user.id != @animal.user.id? %>
      <div class="follow">
      <%= render "relationships/follow_button", user: @animal.user %>
      </div>
    <% end %>
  </div>
  <div class="content_post">
      <div class="fav">
     <%= render partial: "favorites/favorite", locals: { animal: @animal } %>
  </div>
  <span class="name">
      <a href="/users/<%= @animal.user.id %>">
      <%= @animal.user.nickname %>
      </a>
    </span>
    <p><%= @animal.tweet %></p>
  <%= image_tag @animal.image, class: 'animalpic' %>
    <div class="content_action">
            <% if current_user.id == @animal.user.id %>
     <div class="destroy">
     <%= link_to image_tag("dummy_user.png") ,animal_path(@animal.id), method: :delete %>
     </div>
  <% end %>

  </div>
  </div>
  </div>
   <div class="container">
      <%= form_with(model: [@animal, @comment], local: true) do |form| %>
        <%= form.text_area :text, placeholder: "コメントする", rows: "2" %>
        <%= form.submit "SEND" %>
      <% end %>
      <div class="comments ">
      <h4>＜コメント一覧＞</h4>
      <% @comments.each do |comment| %>
        <p>
          <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
          <%= comment.text %>
        </p>
      <% end %>
    </div>
  </div>
</div>
<%= render partial: "ber/sideber"%>

app/views/animals/update.html.erb
<div class="contents row">
  <div class="success">
    <h3>更新が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/favorites/_favorite.html.erb
      <% if user_signed_in? %>
    <% if animal.favorited_by?(current_user) %> <!-- ログインしているユーザーがファボしたかどうかで分岐 -->
  <a><span>❤︎</span><%=link_to animal.favorites.count, animal_favorites_path(animal.id), method: :delete %></a>
    <% else %>
  <a><span>♡</span><%=link_to animal.favorites.count, animal_favorites_path(animal.id), method: :post %></a>
    <% end %>
  <% else %>
    <p><span>❤︎</span><%= animal.favorites.count %></p>
  <% end %>

app/views/favorites/create.html.erb
<h1>Favorites#create</h1>
<p>Find me in app/views/favorites/create.html.erb</p>

app/views/favorites/destroy.html.erb
<h1>Favorites#destroy</h1>
<p>Find me in app/views/favorites/destroy.html.erb</p>

app/views/favorites/show.html.erb
<div class="contents row">
<% if @favorite_animals.exists? %>
<% @favorite_animals.each do |animal| %>
   <%= render partial: "animals/animal", locals: { animal: animal } %>
<% end %>
<% else %>
  <p>お気に入りはありません</p>
<% end %>
</div>
</div>
<%= render partial: "ber/sideber"%>

app/views/relationships/_follow_button.html.erb
<% if current_user.following?(user) %>
  <%= link_to image_tag('follow2.png',class:'follow-btn'),user_relationships_path(user.id), method: :delete %>
<% else %>
  <%= link_to  image_tag('follow1.png',class:'follow-btn'),user_relationships_path(user.id), method: :post %>
<% end %>

app/views/relationships/followers.html.erb
<div class="contents row">
<h2>フォローされているユーザー</h2>
<% if @users.exists? %>
  <thead>
    <tr>
      <th>name</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.nickname %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <p>ユーザーはいません</p>
<% end %>
</div>

app/views/relationships/followings.html.erb
<div class="contents row">
<h2>フォローしているユーザー</h2>
<% if @users.exists? %>
  <thead>
    <tr>
      <th>name</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.nickname %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <p>ユーザーはいません</p>
<% end %>
</div>

app/views/relationships/show.html.erb
<h2>Follower Users</h2>
<% if @users.exists? %>
  <thead>
    <tr>
      <th>name</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/users/edit.html.erb
<div class="contents row ">
  <div class="container">
    <h2>プロフィールを編集</h2>
    <%= form_with(model:@user, local: true) do |f| %>
    <%= render 'animals/error_messages', model: f.object %>

            プロフィール画像
        <span class="indispensable"></span>
      <div class="click-upload">
          クリックしてファイルをアップロード
        <%= f.file_field :image, id:"select-image" %>
    </div>
            <div class= "preview">
            <%= image_tag 'pure.png' %>
        <div id="image-list">
        </div>
        </div>
            <div class="field">
        <%= f.label :nickname %> <em>(6 characters maximum)</em><br />
        <%= f.text_field :nickname, autofocus: true, maxlength: "6" %>
      </div>
      <div class="field">
          テキスト
      <%= f.text_area :profile, rows: "5" %>
      </div>

      <div class="actions">
        <%= f.submit "送信" %>
      </div>
    <% end %>
  </div>
</div>
<%= render partial: "ber/sideber"%>

app/views/users/show.html.erb
<div class="contents row">
  <div class='pro'>
    <div class='userpage-img'>
    <% if @user.image.present? %>
    <%= image_tag @user.image%>
    <% else %>
    <%= image_tag "dummy_user.png" %>
    <% end %>
    </div>
    <div class='userpage-text'>
    <% if current_user.id == @user.id %>
    <% else %>
      <div class="user_follow">
      <%= render "relationships/follow_button", user: @user %>
      </div>
    <% end %>
      <div class='userpage-name'>
      <a><%= @user.nickname %></a>
      <% if @user.profile.present? %>
        <div class='userpage-profile'>
        <td><%= safe_join(@user.profile.split("\n"),tag(:br)) %></td>
        </div>
      <% end %>
      <% if current_user.id == @user.id %>
      <%= link_to 'プロフィールを編集', edit_user_path(@user.id),class:"pro_edit" %>
      <% end %>
      </div>
    </div>
  </div>
  <p><%= @user.nickname %>さんの投稿一覧</p>
  <% @animal.each do |animal| %>
  <%= render partial: "animals/animal", locals: { animal: animal } %> 
  <% end %>
</div>
<%= render partial: "ber/sideber"%>